# ------------------------------------------------------------------------------
# Travis CI scripts
# Copyright(c) pgRouting Contributors
#
# Main configuration
# ------------------------------------------------------------------------------

dist: trusty
sudo: required


language: python
python:
  - "3.5-dev"  # 3.5 development branch

packages:
  -  pyqt5-dev-tools


install:
  - pip install -r requirements.txt

script:
  - pb_tool compile
  - mkdocs build

