site_name: pgRoutingLayer
nav:
- Home: index.md
- Introduction:
  - Main buttons: intro/buttons.md
  - Layer naming convention: intro/layer_naming_convention.md
- Functions:
  - pgr_djikstra: functions/pgr_dijkstra.md
theme: readthedocs
