site_name: pgRoutingLayer
nav:
- Home: index.md
- Functions:
  - Djikstra: functions/pgr_dijkstra.md
  - Astar: functions/pgr_astar.md
  - bdDijkstra: functions/pgr_bddijkstra.md
  - bdAstar: functions/pgr_bdastar.md
theme: readthedocs
