site_name: pgRoutingLayer
nav:
- Home: index.md
- Introduction:
  - Main buttons: intro/buttons.md
  - Layer naming convention: intro/layer_naming_convention.md
- Functions:
  - pgr_djikstra: functions/pgr_dijkstra.md
  - pgr_KSP: functions/pgr_KSP.md
  - pgr_aStar: functions/pgr_aStar.md
  - pgr_bdAstar: functions/pgr_bdAstar.md
  - pgr_bdDijkstra: functions/pgr_bdDijkstra.md
theme: readthedocs
